CREATE TABLE Clientes (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100), Telefone NVARCHAR(20), Endereco NVARCHAR(200), Cpf NVARCHAR(20), Status BIT DEFAULT 1
);

CREATE TABLE Pizzas (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Sabor NVARCHAR(100), Ingredientes NVARCHAR(MAX), Preco DECIMAL(10,2), Status BIT DEFAULT 1
);

CREATE TABLE OutrosProdutos (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100), Preco DECIMAL(10,2), Status BIT DEFAULT 1
);

CREATE TABLE Pedidos (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ClienteId INT, PizzaId INT, QtdPizza INT, ValorTotal DECIMAL(10,2), 
    Status NVARCHAR(50), FormaPagamento NVARCHAR(50), DetalhesJson NVARCHAR(MAX), DataHora DATETIME DEFAULT GETDATE()
);